chore: migrate to npm

diff --git a/.github/workflows/gh-pages.yml b/.github/workflows/gh-pages.yml
--- a/.github/workflows/gh-pages.yml
+++ b/.github/workflows/gh-pages.yml
@@ -14,24 +14,46 @@ concurrency:
   group: "pages"
   cancel-in-progress: true
 
+env:
+  BUILD_PATH: "./starters/gatsby-starter-aoi-theme" # default value when not using subfolders
+
 jobs:
   build:
     name: Build
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
+      - uses: actions/checkout@v4
+
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
       
       - name: Setup Node.js
         uses: actions/setup-node@v3
         with:
           node-version: 'lts/*'
-          cache: yarn
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+          cache-dependency-path: ./package-lock.json
       
       - name: Setup Pages
         id: pages
-        uses: actions/configure-pages@v2
+        uses: actions/configure-pages@v3
+        with:
+          static_site_generator: gatsby
 
       - name: Restore cache
         uses: actions/cache@v3
@@ -44,13 +66,13 @@ jobs:
             ${{ runner.os }}-gatsby-build-
 
       - name: Install dependencies
-        run: yarn install --immutable
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
 
       - name: Build theme
-        run: yarn run build
+        run: ${{ steps.detect-package-manager.outputs.manager }} run build
 
       - name: Build starter
-        run: yarn run build:starter
+        run: ${{ steps.detect-package-manager.outputs.manager }} run build:starter
 
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v1
